version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  build:
    commands:
      - cd Backend/
      - mvn clean install
      - mvn package
      - echo build
  post_build:
    commands:
      - echo "$PWD"
      - cd ../
      - echo "$PWD"
      - cp -a Backend/target/*.jar .
      - echo Build completed
artifacts:
  files:
    - *.jar
    - scripts/*.sh
    - appspec.yml