version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  build:
    commands:
      - cd Backend/
      - mvn clean install
      - mvn package
      - echo build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/bot-0.0.1-SNAPSHOT.jar
    - target/*.jar
    - scripts/*.sh
    - appspec.yml